[2020-05-02 12:17:44] Exception occurred in repo https://github.com/ProjectIgnis/Puzzles: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:17:44] Exception occurred in repo https://github.com/ProjectIgnis/LFLists: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:17:44] Exception occurred in repo https://github.com/ProjectIgnis/DeltaHopeHarbinger: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:17:44] The repo https://github.com/ProjectIgnis/DeltaHopeHarbinger couldn't be cloned
[2020-05-02 12:17:44] Error: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:17:44] The repo https://github.com/ProjectIgnis/LFLists couldn't be cloned
[2020-05-02 12:17:44] Error: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:17:44] The repo https://github.com/ProjectIgnis/Puzzles couldn't be cloned
[2020-05-02 12:17:44] Error: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:18:30] The repo https://github.com/ProjectIgnis/DeltaHopeHarbinger couldn't be cloned
[2020-05-02 12:18:30] Error: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:18:30] The repo https://github.com/ProjectIgnis/LFLists couldn't be cloned
[2020-05-02 12:18:30] Error: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-02 12:18:30] The repo https://github.com/ProjectIgnis/Puzzles couldn't be cloned
[2020-05-02 12:18:30] Error: failed to send request: O nome ou o endere√ßo do servidor n√£o p√¥de ser resolvido

[2020-05-15 12:22:43] Warning occurred in repo https://github.com/ProjectIgnis/Puzzles: failed to send request: O tempo limite da opera√ß√£o foi atingido

[2020-05-15 12:39:29] Exception occurred while loading configs.json: [json.exception.parse_error.101] parse error at line 16, column 60: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"Project Batata TraduÁ„'
[2020-05-15 12:40:04] Exception occurred while loading configs.json: [json.exception.parse_error.101] parse error at line 16, column 60: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"Project Batata TraduÁ„'
[2020-05-15 12:40:35] Exception occurred while loading configs.json: [json.exception.parse_error.101] parse error at line 16, column 60: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"Project Batata TraduÁ„'
[2020-05-15 12:41:55] Exception occurred while loading configs.json: [json.exception.parse_error.101] parse error at line 16, column 60: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"Project Batata TraduÁ„'
[2020-05-15 12:43:53] Exception occurred while loading configs.json: [json.exception.parse_error.101] parse error at line 31, column 60: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"Project Batata TraduÁ„'
[2020-07-25 15:44:34] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/PEDRO/Desktop/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2020-07-28 21:27:05] The repo https://github.com/ProjectIgnis/DeltaHopeHarbinger couldn't be cloned
[2020-07-28 21:27:05] Error: failed to resolve path '././repositories/delta': O sistema n√£o pode encontrar o caminho especificado.

[2020-07-28 21:27:06] The repo https://github.com/ProjectIgnis/LFLists couldn't be cloned
[2020-07-28 21:27:06] Error: failed to resolve path '././repositories/lflists': O sistema n√£o pode encontrar o caminho especificado.

[2020-07-28 21:27:06] The repo https://github.com/ProjectIgnis/Puzzles couldn't be cloned
[2020-07-28 21:27:06] Error: failed to resolve path '././puzzles/Canon collection': O sistema n√£o pode encontrar o caminho especificado.

[2020-07-28 21:27:06] The repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br couldn't be cloned
[2020-07-28 21:27:06] Error: failed to resolve path '././config/languages': O sistema n√£o pode encontrar o caminho especificado.

[2021-01-12 14:39:01] Exception occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: reference 'refs/heads/master' not found
[2021-01-12 14:39:01] The repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR couldn't be cloned
[2021-01-12 14:39:01] Error: reference 'refs/heads/master' not found
[2021-01-12 14:40:08] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: revspec 'HEAD' not found
[2021-01-12 14:40:08] Exception occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: reference 'refs/heads/master' not found
[2021-01-12 14:40:08] The repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR couldn't be cloned
[2021-01-12 14:40:08] Error: reference 'refs/heads/master' not found
[2021-01-12 14:41:07] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: revspec 'HEAD' not found
[2021-01-12 14:41:07] Exception occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: reference 'refs/heads/master' not found
[2021-01-12 14:41:07] The repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR couldn't be cloned
[2021-01-12 14:41:07] Error: reference 'refs/heads/master' not found
[2021-01-12 14:44:55] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: revspec 'HEAD' not found
[2021-01-12 14:44:55] Exception occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR: reference 'refs/heads/master' not found
[2021-01-12 14:44:55] The repo https://github.com/Garoto-Batata/Project-Batata-Translation-PTBR couldn't be cloned
[2021-01-12 14:44:55] Error: reference 'refs/heads/master' not found
[2021-02-18 10:34:33] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Usuario/Desktop/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2021-05-19 21:50:23] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Usuario/Desktop/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2021-05-25 13:50:43] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Usuario/Desktop/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2021-07-22 16:28:48] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Usuario/Documents/Pastas/EdoproMod/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2021-08-19 21:49:19] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Usuario/Documents/Pastas/EdoproMod/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2021-08-19 21:50:21] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Usuario/Documents/Pastas/EdoproMod/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2021-12-12 18:18:55] [Erro de script]: [string "./puzzles/Canon collection/Puzzle Creator.lua..."]:16: attempt to call a nil value (global 'require')
[2021-12-12 18:18:59] [Erro de script]: [string "./puzzles/Canon collection/Puzzle Creator.lua..."]:16: attempt to call a nil value (global 'require')
[2021-12-12 18:19:06] [Erro de script]: [string "./puzzles/Canon collection/convert to goat.lu..."]:8: attempt to call a nil value (global 'require')
[2021-12-13 11:32:39] [Erro de script]: [string "./puzzles/Canon collection/Puzzle Creator.lua..."]:16: attempt to call a nil value (global 'require')
[2021-12-13 11:32:58] [Erro de script]: [string "./puzzles/Canon collection/convert to goat.lu..."]:8: attempt to call a nil value (global 'require')
[2021-12-13 15:52:14] Exception occurred: Host not resolved
[2024-01-05 16:34:30] bad allocation
[2024-01-05 16:34:33] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: indexer progress callback returned -1
[2024-01-06 19:49:39] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Downloads/Letra X Y Z/EDOPro ZDD/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2024-01-08 19:13:02] [Erro de script]: [string "./puzzles/Canon collection/convert to goat.lu..."]:8: attempt to call a nil value (global 'require')
[2024-01-09 18:36:29] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: the index is locked; this might be due to a concurrent or crashed process
[2024-01-09 20:58:13] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-09 20:59:10] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: indexer progress callback returned -1
[2024-01-10 00:51:02] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: indexer progress callback returned -1
[2024-01-10 00:57:26] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: indexer progress callback returned -1
[2024-01-10 01:06:06] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: indexer progress callback returned -1
[2024-01-10 02:00:27] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-10 02:04:04] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-10 02:05:30] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-10 20:03:36] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-10 20:04:09] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-10 20:25:21] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-10 20:30:22] Exception occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-01-11 01:54:58] [Erro de script]: [string "./puzzles/Generated Puzzle 3.lua"]:65: attempt to index a nil value (global 'm_0')
[2024-01-11 01:55:01] [Erro de script]: [string "./puzzles/Generated Puzzle 3.lua"]:65: attempt to index a nil value (global 'm_0')
[2024-01-11 01:57:13] [Erro de script]: [string "./puzzles/Generated Puzzle 3.lua"]:65: attempt to index a nil value (global 'm_0')
[2024-01-11 01:57:21] [Erro de script]: [string "./puzzles/Generated Puzzle 3.lua"]:65: attempt to index a nil value (global 'm_0')
[2024-01-11 01:58:09] [Erro de script]: [string "./puzzles/Generated Puzzle 3.lua"]:65: attempt to index a nil value (global 'm_0')
[2024-01-14 18:03:04] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: Undefined error
[2024-01-14 18:03:06] Warning occurred in repo https://github.com/ProjectIgnis/Puzzles: the index is locked; this might be due to a concurrent or crashed process
[2024-01-14 18:03:07] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: the index is locked; this might be due to a concurrent or crashed process
[2024-01-23 21:50:03] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: failed to lock file 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/repositories/delta-puppet/.git/refs/heads/master.lock' for writing: 
[2024-01-24 16:03:35] [Erro de script]: [string "./puzzles/Tudo.lua"]:57: syntax error near 'em'
[2024-01-24 16:03:44] [Erro de script]: [string "./puzzles/Tudo.lua"]:57: syntax error near 'em'
[2024-01-24 16:03:58] [Erro de script]: [string "./puzzles/Tudo.lua"]:57: syntax error near 'em'
[2024-01-24 16:04:03] [Erro de script]: [string "./puzzles/Tudo.lua"]:57: syntax error near 'em'
[2024-01-24 16:11:15] [Erro de script]: stack traceback:
[2024-01-24 16:11:15] [Erro de script]: 	[string "./puzzles/Tudo.lua"]:65: in main chunk
[2024-01-24 16:11:15] [Erro de script]: "CallCardFunction"(c73335319.initial_effect): attempt to call an error function
[2024-01-24 16:23:48] [Erro de script]: stack traceback:
[2024-01-24 16:23:48] [Erro de script]: 	[string "./puzzles/Tudo.lua"]:60: in main chunk
[2024-01-24 16:23:48] [Erro de script]: "CallCardFunction"(c91130731.initial_effect): attempt to call an error function
[2024-02-05 00:36:19] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: corrupted loose reference file: FETCH_HEAD
[2024-02-05 00:36:19] Warning occurred in repo https://github.com/ProjectIgnis/LFLists: corrupted loose reference file: FETCH_HEAD
[2024-02-05 00:36:20] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: Undefined error
[2024-02-08 15:31:14] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2024-02-09 02:00:54] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2024-02-09 02:44:27] Error when loading database (./config/languages/Portugu√™s/cards.cdb): no such table: texts
[2024-05-06 02:09:24] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-07-21 06:30:48] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2024-08-02 08:22:08] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: Undefined error
[2025-01-07 13:41:44] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2025-03-20 14:33:40] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2025-03-24 11:29:29] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2025-03-26 15:37:21] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: could not remove 'C:/Users/Daniel/Documents/PC-  Notas/YGO-EDOPro/config/languages/Portugu√™s/cards.cdb': O arquivo j√° est√° sendo usado por outro processo.

[2025-03-30 18:04:21] Warning occurred in repo https://github.com/ProjectIgnis/LFLists: corrupted loose reference file: FETCH_HEAD
[2025-03-30 18:04:23] Warning occurred in repo https://github.com/Garoto-Batata/Project-Batata-Translation-Pt-Br: the index is locked; this might be due to a concurrent or crashed process
[2025-03-30 18:04:28] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: the index is locked; this might be due to a concurrent or crashed process
[2025-03-30 18:04:54] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: the index is locked; this might be due to a concurrent or crashed process
[2025-03-30 18:04:54] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: the index is locked; this might be due to a concurrent or crashed process
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:44:48] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:45:07] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:45:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:46:02] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:46:24] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:48:23] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 19:50:49] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:50:49] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:50:49] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:50:49] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:50:49] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:50:49] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:50:49] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:52:29] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:52:29] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:52:29] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:52:29] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:52:29] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:52:29] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:52:29] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:52:48] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:52:48] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:52:48] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:52:48] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:52:48] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:52:48] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:52:48] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:53:08] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:53:08] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:53:08] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:53:08] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:53:08] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:53:08] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:53:08] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:53:33] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:53:33] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:53:33] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:53:33] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:53:33] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:53:33] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:53:33] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:54:06] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:54:06] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:54:06] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:54:06] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:54:06] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:54:06] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:54:06] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:54:16] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:54:16] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:54:16] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:54:16] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:54:16] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:54:16] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:54:16] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:54:49] [Erro de script]: [string "c999.lua"]:11: <name> expected near 'end'
[2025-04-03 19:54:49] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:54:49] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:54:49] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 19:54:49] [Erro de script]: "CallCardFunction"(c999.initial_effect): attempt to call an error function
[2025-04-03 19:54:49] [Erro de script]: "CallCardFunction"(c2.initial_effect): attempt to call an error function
[2025-04-03 19:54:49] [Erro de script]: "CallCardFunction"(c1.initial_effect): attempt to call an error function
[2025-04-03 20:00:43] [Erro de script]: [string "c111000001.lua"]:16: attempt to index a nil value (global 'e2')
[2025-04-03 20:00:43] [Erro de script]: [string "c111000001.lua"]:16: attempt to index a nil value (global 'e2')
[2025-04-03 20:00:43] [Erro de script]: [string "c111000001.lua"]:16: attempt to index a nil value (global 'e2')
[2025-04-03 20:00:43] [Erro de script]: [string "c111000001.lua"]:16: attempt to index a nil value (global 'e2')
[2025-04-03 20:00:43] [Erro de script]: [string "c111000001.lua"]:16: attempt to index a nil value (global 'e2')
[2025-04-03 20:00:43] [Erro de script]: [string "c111000001.lua"]:16: attempt to index a nil value (global 'e2')
[2025-04-03 20:29:03] [Erro de script]: [string "c111000001.lua"]:19: unexpected symbol near 'and'
[2025-04-03 20:29:03] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:03] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:03] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:03] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:39] [Erro de script]: [string "c111000001.lua"]:19: unexpected symbol near 'and'
[2025-04-03 20:29:39] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:39] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:39] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:29:39] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:30:34] [Erro de script]: [string "c111000001.lua"]:19: unexpected symbol near 'and'
[2025-04-03 20:30:34] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:30:34] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:30:34] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 20:30:34] [Erro de script]: "CallCardFunction"(c111000001.initial_effect): attempt to call an error function
[2025-04-03 21:35:07] [Erro de script]: stack traceback:
[2025-04-03 21:35:07] [Erro de script]: 	[string "c111000001.lua"]:37: in function <[string "c111000001.lua"]:27>
[2025-04-03 21:35:07] [Erro de script]: [string "c111000001.lua"]:37: Parameter 2 should be "Int" but is "nil".
[2025-04-04 15:34:48] [Erro de script]: [string "c111000002.lua"]:22: attempt to call a nil value (field 'MoveToHand')
[2025-04-04 15:36:04] [Erro de script]: [string "c111000002.lua"]:24: attempt to call a nil value (field 'MoveToHand')
[2025-04-05 18:01:11] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:01:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:36] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:01:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:39] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:01:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:43] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:01:43] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:43] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:43] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:43] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:43] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:01:43] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:12] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:02:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:12] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:23] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:02:23] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:23] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:23] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:23] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:23] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:23] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:44] [Erro de script]: [string "c111000003.lua"]:12: unexpected symbol near '-'
[2025-04-05 18:02:44] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:44] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:44] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:44] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:44] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:02:44] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:34] [Erro de script]: [string "c111000003.lua"]:10: unexpected symbol near '-'
[2025-04-05 18:04:34] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:34] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:34] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:34] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:34] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:34] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:57] [Erro de script]: [string "c111000003.lua"]:10: unexpected symbol near '-'
[2025-04-05 18:04:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:04:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:20] [Erro de script]: [string "c111000003.lua"]:25: 'then' expected near 'local'
[2025-04-05 18:05:20] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:20] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:20] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:20] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:20] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:20] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:57] [Erro de script]: [string "c111000003.lua"]:25: 'then' expected near 'local'
[2025-04-05 18:05:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:05:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:06:57] [Erro de script]: [string "c111000003.lua"]:25: 'then' expected near 'local'
[2025-04-05 18:06:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:06:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:06:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:06:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:06:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:06:57] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:08:39] [Erro de script]: [string "c111000003.lua"]:26: 'then' expected near 'local'
[2025-04-05 18:08:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:08:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:08:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:08:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:08:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:08:39] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:00] [Erro de script]: [string "c111000003.lua"]:25: 'then' expected near 'local'
[2025-04-05 18:10:00] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:00] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:00] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:00] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:00] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:00] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:40] [Erro de script]: [string "c111000003.lua"]:25: 'then' expected near 'local'
[2025-04-05 18:10:40] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:40] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:40] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:40] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:40] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:10:40] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:11:30] [Erro de script]: [string "c111000003.lua"]:25: 'then' expected near 'local'
[2025-04-05 18:11:30] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:11:30] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:11:30] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:11:30] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:11:30] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:11:30] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:20:15] [Erro de script]: [string "c111000003.lua"]:30: 'then' expected near 'local'
[2025-04-05 18:20:15] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:20:15] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:20:15] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:20:15] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:20:15] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:20:15] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:22:58] [Erro de script]: [string "c111000003.lua"]:30: 'then' expected near 'local'
[2025-04-05 18:22:58] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:22:58] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:22:58] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:22:58] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:22:58] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:22:58] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 18:24:54] [Erro de script]: [string "c111000003.lua"]:31: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 18:24:54] [Erro de script]: [string "c111000003.lua"]:31: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 18:24:54] [Erro de script]: [string "c111000003.lua"]:31: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 18:27:33] [Erro de script]: [string "c111000003.lua"]:31: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 18:27:33] [Erro de script]: [string "c111000003.lua"]:31: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 18:27:33] [Erro de script]: [string "c111000003.lua"]:31: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 18:32:32] [Erro de script]: [string "c111000003.lua"]:32: attempt to call a nil value (field 'ConfirmCard')
[2025-04-05 19:42:22] [Erro de script]: [string "c111000003.lua"]:41: syntax error near 'local'
[2025-04-05 19:42:22] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 19:42:22] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 19:42:22] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 19:42:36] [Erro de script]: [string "c111000003.lua"]:41: syntax error near 'local'
[2025-04-05 19:42:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 19:42:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-05 19:42:36] [Erro de script]: "CallCardFunction"(c111000003.initial_effect): attempt to call an error function
[2025-04-07 02:41:20] [Erro de script]: [string "c111000004.lua"]:30: 'end' expected (to close 'function' at line 21) near <eof>
[2025-04-07 02:41:20] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:41:20] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:41:20] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:41:20] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:41:20] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:41:20] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:42:23] [Erro de script]: [string "c111000004.lua"]:30: 'end' expected (to close 'function' at line 21) near <eof>
[2025-04-07 02:42:23] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:42:23] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:42:23] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:42:23] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:42:23] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:42:23] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:43:07] [Erro de script]: [string "c111000004.lua"]:4: attempt to index a nil value (global 's')
[2025-04-07 02:43:07] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:43:07] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:43:07] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:43:07] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:43:07] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 02:43:07] [Erro de script]: "CallCardFunction"(c111000004.initial_effect): attempt to call an error function
[2025-04-07 11:05:01] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 11:05:02] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 11:05:02] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 11:05:02] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 11:05:02] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 11:05:02] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 12:14:38] [Erro de script]: [string "c111000011.lua"]:13: unexpected symbol near '-'
[2025-04-07 12:14:38] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 12:14:38] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 12:14:38] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 12:14:38] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 12:14:38] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 12:14:38] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:36:13] [Erro de script]: [string "c111000011.lua"]:28: 'end' expected (to close 'function' at line 19) near <eof>
[2025-04-07 18:36:14] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:36:14] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:36:14] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:36:14] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:36:14] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:36:14] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:37:04] [Erro de script]: [string "c111000011.lua"]:28: 'end' expected (to close 'function' at line 19) near <eof>
[2025-04-07 18:37:04] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:37:04] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:37:04] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:37:04] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:37:04] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:37:04] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:27] [Erro de script]: [string "c111000011.lua"]:29: 'end' expected (to close 'function' at line 4) near <eof>
[2025-04-07 18:38:27] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:27] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:27] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:27] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:27] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:27] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:55] [Erro de script]: [string "c111000011.lua"]:29: 'end' expected (to close 'function' at line 4) near <eof>
[2025-04-07 18:38:55] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:55] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:55] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:55] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:55] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:38:55] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:43:43] [Erro de script]: [string "c111000011.lua"]:31: syntax error near '!'
[2025-04-07 18:43:43] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:43:43] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:43:43] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:43:43] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:43:43] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-07 18:43:43] [Erro de script]: "CallCardFunction"(c111000011.initial_effect): attempt to call an error function
[2025-04-08 05:52:46] [Erro de script]: [string "c111999011.lua"]:23: Parameter 2 should be "Function" but is "nil".
[2025-04-08 05:52:46] [Erro de script]: [string "c111999011.lua"]:23: Parameter 2 should be "Function" but is "nil".
[2025-04-08 05:53:23] [Erro de script]: [string "c111999011.lua"]:23: Parameter 2 should be "Function" but is "nil".
[2025-04-08 05:53:23] [Erro de script]: [string "c111999011.lua"]:23: Parameter 2 should be "Function" but is "nil".
[2025-04-12 22:12:26] Warning occurred in repo https://github.com/Yoshi80/Rush-HD-Pictures: the index is locked; this might be due to a concurrent or crashed process
[2025-04-12 22:12:33] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: the index is locked; this might be due to a concurrent or crashed process
[2025-04-12 22:50:00] [Erro de script]: stack traceback:
[2025-04-12 22:50:00] [Erro de script]: 	[string "./puzzles/Generated Puzzle10.lua"]:28: in main chunk
[2025-04-12 22:50:00] [Erro de script]: "CallCardFunction"(c23557833.initial_effect): attempt to call an error function
[2025-04-12 22:51:26] [Erro de script]: stack traceback:
[2025-04-12 22:51:26] [Erro de script]: 	[string "./puzzles/Generated Puzzle10.lua"]:28: in main chunk
[2025-04-12 22:51:26] [Erro de script]: "CallCardFunction"(c23557833.initial_effect): attempt to call an error function
[2025-04-12 22:51:51] [Erro de script]: stack traceback:
[2025-04-12 22:51:51] [Erro de script]: 	[string "./puzzles/Generated Puzzle10.lua"]:28: in main chunk
[2025-04-12 22:51:51] [Erro de script]: "CallCardFunction"(c23557833.initial_effect): attempt to call an error function
